apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpoapp
  labels:
    app: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: araragiqte/vprofileapp:v1
          ports:
            - name: vproapp-port
              containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
        - name: init-mydb
          image: busybox
          command: [ 'sh', '-c', 'until nslookup vprocached01; do echo waiting for mycache; sleep 2; done;' ]